# Generated by Django 3.2.5 on 2021-07-20 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaData',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('search', models.TextField()),
                ('summary', models.TextField()),
                ('cached_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wikidata',
            },
        ),
    ]
